runtime: python39
entrypoint: gunicorn -b :$PORT backend.wsgi

env_variables:
  DJANGO_SETTINGS_MODULE: "backend.settings"
  SECRET_KEY: "your-secret-key-here"
  DEBUG: "False"
  ENV: "prod"
  DB_NAME: "mls"
  DB_USER: "postgres"
  DB_PASSWORD: "your-db-password"
  DB_HOST: "/cloudsql/YOUR_PROJECT_ID:REGION:INSTANCE_NAME"

handlers:
- url: /static
  static_dir: staticfiles
- url: /.*
  script: auto

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10 