# Generated by Django 5.1.2 on 2024-10-26 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('number_of_rooms', models.IntegerField()),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('building_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mls.buildingmanager')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mls.flat')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_type', models.CharField(max_length=50)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mls.flat')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mls.tenant')),
            ],
        ),
    ]
