# Generated by Django 5.1.2 on 2024-10-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flat',
            name='flat_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flat',
            name='post_code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
