# Generated by Django 5.1.2 on 2024-10-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0002_flat_city_flat_flat_name_flat_post_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='post_code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
