# Generated by Django 5.1.2 on 2024-10-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0003_tenant_address_tenant_city_tenant_post_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_month',
            field=models.DateField(blank=True, null=True),
        ),
    ]
