# Generated by Django 5.1.2 on 2024-10-26 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0004_payment_payment_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildingmanager',
            options={'verbose_name': 'Gestionnaire', 'verbose_name_plural': 'Gestionnaires'},
        ),
        migrations.AlterModelOptions(
            name='flat',
            options={'verbose_name': 'Appartement', 'verbose_name_plural': 'Appartements'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'verbose_name': 'Locataire', 'verbose_name_plural': 'Locataires'},
        ),
        migrations.AlterField(
            model_name='buildingmanager',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='buildingmanager',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom du gestionnaire'),
        ),
        migrations.AlterField(
            model_name='buildingmanager',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='building_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mls.buildingmanager', verbose_name='Gestionnaire'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='flat_name',
            field=models.CharField(max_length=100, verbose_name="Nom de l'appartement"),
        ),
        migrations.AlterField(
            model_name='flat',
            name='number_of_rooms',
            field=models.IntegerField(verbose_name='Nombre de chambres'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='post_code',
            field=models.CharField(max_length=20, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant du loyer'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mls.flat', verbose_name='Appartement'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(verbose_name='Date de paiement'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_month',
            field=models.DateField(blank=True, null=True, verbose_name='Mois de paiement'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('loyer', 'Loyer'), ('ajustement_charge', 'Ajustement Charge'), ('autre', 'Autre')], max_length=50, verbose_name='Type de paiement'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mls.tenant', verbose_name='Locataire'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mls.flat', verbose_name='Appartement'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom du locataire'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='post_code',
            field=models.CharField(max_length=20, verbose_name='Code postal'),
        ),
    ]
