# Generated by Django 5.1.2 on 2024-10-26 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0006_tenant_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(choices=[('rent_receipt', 'Rent Receipt'), ('annual_receipt', 'Annual Receipt')], max_length=20, verbose_name='Type de communication')),
                ('date_sent', models.DateField(verbose_name="Date d'envoi")),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='mls.tenant', verbose_name='Locataire')),
            ],
            options={
                'verbose_name': 'Communication',
                'verbose_name_plural': 'Communications',
            },
        ),
    ]
