# Generated by Django 5.1.2 on 2024-10-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0009_flat_landlord'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='utilities_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant des charges'),
        ),
    ]
