# Generated by Django 5.1.2 on 2024-11-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0012_communication_reference_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('backup', 'Backup'), ('restore', 'Restore')], max_length=7)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='success', max_length=50)),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backups',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='communication',
            name='communication_type',
            field=models.CharField(choices=[('rent_receipt', 'Rent Receipt'), ('annual_receipt', 'Annual Receipt'), ('missing_payment_notice', 'Missing Payment Notice'), ('other', 'Autre')], max_length=40, verbose_name='Type de communication'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Numéro de téléphone'),
        ),
    ]
