# Generated by Django 5.1.2 on 2024-11-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0014_backup_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='address',
            field=models.CharField(default=1, max_length=255, verbose_name='Adresse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landlord',
            name='city',
            field=models.CharField(default=1, max_length=100, verbose_name='Ville'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landlord',
            name='post_code',
            field=models.CharField(default=1, max_length=20, verbose_name='Code postal'),
            preserve_default=False,
        ),
    ]
