# Generated by Django 5.1.2 on 2024-11-03 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0018_alter_communication_communication_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilitiesAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_year', models.IntegerField(verbose_name='Année de référence')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant de la régularisation')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Payé')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mls.flat', verbose_name='Appartement')),
            ],
            options={
                'verbose_name': 'Régularisation des charges',
                'verbose_name_plural': 'Régularisations des charges',
                'unique_together': {('flat', 'reference_year')},
            },
        ),
    ]
