# Generated by Django 5.1.2 on 2024-11-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0019_utilitiesadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de sortie'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Locataire actif'),
        ),
    ]
