# Generated by Django 5.1.2 on 2024-11-03 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0020_tenant_end_date_tenant_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='flat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mls.flat', verbose_name='Appartement'),
        ),
    ]
