# Generated by Django 5.1.2 on 2024-11-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0021_alter_tenant_flat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilitiesadjustment',
            name='amount',
        ),
        migrations.AddField(
            model_name='utilitiesadjustment',
            name='heating_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant chauffage'),
        ),
        migrations.AddField(
            model_name='utilitiesadjustment',
            name='lift_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant ascenseur'),
        ),
    ]
