# Generated by Django 5.1.2 on 2024-11-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0022_remove_utilitiesadjustment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Montant du dépôt de garantie'),
        ),
    ]
