# Generated by Django 5.1.2 on 2024-11-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0025_utilitiesadjustment_other_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='communication_type',
            field=models.CharField(choices=[('rent_receipt', 'Rent Receipt'), ('annual_receipt', 'Annual Receipt'), ('missing_payment_notice', 'Missing Payment Notice'), ('rent_notice', 'Rent Notice'), ('charges_notice', 'Régularisation des charges'), ('other', 'Autre')], max_length=40, verbose_name='Type de communication'),
        ),
    ]
