# Generated by Django 5.1.2 on 2024-11-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0027_alter_communication_communication_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlordexpense',
            name='reference_month',
            field=models.DateField(blank=True, help_text='Month and year this expense is for (YYYY-MM)', null=True, verbose_name='Mois de référence'),
        ),
    ]
