# Generated by Django 5.1.2 on 2024-11-20 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0028_landlordexpense_reference_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant de la charge')),
                ('charge_type', models.CharField(choices=[('ordures_menageres', 'Ordures Ménagères'), ('entretien', 'Entretien'), ('autre', 'Autre')], max_length=50, verbose_name='Type de charge')),
                ('reference_month', models.DateField(verbose_name='Mois de référence')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mls.flat', verbose_name='Appartement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mls.tenant', verbose_name='Locataire')),
            ],
            options={
                'verbose_name': 'Charge supplémentaire',
                'verbose_name_plural': 'Charges supplémentaires',
                'ordering': ['-reference_month'],
            },
        ),
    ]
