# Generated by Django 5.1.2 on 2024-11-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0029_extracharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='expected_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant attendu'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant Loyer'),
        ),
    ]
