# Generated by Django 5.1.2 on 2024-11-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0030_payment_expected_amount_alter_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='expected_amount',
        ),
    ]
