# Generated by Django 5.1.2 on 2024-11-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0031_remove_payment_expected_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitiesadjustment',
            name='reference_month',
            field=models.DateField(blank=True, help_text='Month and year this expense is for (YYYY-MM)', null=True, verbose_name='Mois de référence'),
        ),
    ]
